version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DOCKER_ENV=true
      - DATABASE_URL=postgresql://user:password@postgres:5432/crewplots
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017/crewplots
    depends_on:
      - postgres
      - redis
      - mongo
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=crewplots
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=crewplots

volumes:
  postgres_data:
  redis_data:
  mongo_data: